spring:
  application:
    name: travel-client

  cloud:
    services:
      registrationMethod: direct

feign:
  hystrix:
    enabled: true

server:
  port: 0

security:
  basic:
    enabled: false

logging:
  level:
    ninja:
      spring:
        DestinationClient: DEBUG